version: "3.3"

services:
    mongo:
        command: --nojournal
        image: mongo:3.4
        logging:
            options:
                max-size: 1m
        networks:
            - validator
        restart: unless-stopped
        volumes:
            - /home/ubuntu/validator/mongo/:/data/db/

    json-iotagent:
        depends_on:
            - json-mosquitto
            - json-orion
        image: fiware/iotagent-json:latest
        logging:
            options:
                max-size: 1m
        networks:
            - validator
        restart: unless-stopped
        volumes:
            - "/home/ubuntu/validator/static/json/config.js:/opt/iotajson/config.js"

    json-mosquitto:
        image: eclipse-mosquitto:1.5
        logging:
            options:
                max-size: 1m
        networks:
            - validator
        restart: unless-stopped
        volumes:
            - "/home/ubuntu/validator/static/json/mosquitto.conf:/mosquitto/config/mosquitto.conf"
            - "/home/ubuntu/validator/json-mosquitto/data/:/mosquitto/data"
            - "/home/ubuntu/validator/json-mosquitto/log/:/mosquitto/log"

    json-orion:
        command: -dbhost mongo -db jsono -logLevel ERROR
        depends_on:
            - mongo
        image: fiware/orion:2.2.0
        logging:
            options:
                max-size: 1m
        networks:
            - validator
        restart: unless-stopped

    ul-iotagent:
        depends_on:
            - ul-mosquitto
            - ul-orion
        image: fiware/iotagent-json:latest
        logging:
            options:
                max-size: 1m
        networks:
            - validator
        restart: unless-stopped
        volumes:
            - "/home/ubuntu/validator/static/ul/config.js:/opt/iotajson/config.js"

    ul-mosquitto:
        image: eclipse-mosquitto:1.5
        logging:
            options:
                max-size: 1m
        networks:
            - validator
        restart: unless-stopped
        volumes:
            - "/home/ubuntu/validator/static/ul/mosquitto.conf:/mosquitto/config/mosquitto.conf"
            - "/home/ubuntu/validator/ul-mosquitto/data/:/mosquitto/data"
            - "/home/ubuntu/validator/ul-mosquitto/log/:/mosquitto/log"

    ul-orion:
        command: -dbhost mongo -db ulo -logLevel ERROR
        depends_on:
            - mongo
        image: fiware/orion:2.2.0
        logging:
            options:
                max-size: 1m
        networks:
            - validator
        restart: unless-stopped

    nginx:
        depends_on:
            - json-iotagent
            - ul-iotagent
        image: repo.lab.fiware.org/nginx:latest
        logging:
            options:
                max-size: 1m
        networks:
            - validator
        ports:
            - "21026:21026"
            - "24061:24061"
            - "27896:27896"
            - "27898:27898"
            - "27897:27897"
        restart: unless-stopped
        volumes:
            - "/home/ubuntu/validator/static/conf.http.d:/etc/nginx/conf.http.d"
            - "/home/ubuntu/validator/static/nginx.conf:/etc/nginx/nginx.conf"
            - "/home/ubuntu/validator/nginx/:/var/log/nginx/"

networks:
  validator:
    external: true
